server:
  port: ${PORT:8080}
spring:
  application:
    name: ansinhso
  threads:
    virtual:
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ansinhso}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:myPassword}
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /v3/api-docs  # Đường dẫn truy cập file JSON cấu hình OpenAPI (Mặc định là /v3/api-docs)
  swagger-ui:
    path: /swagger-ui.html # Đường dẫn truy cập giao diện Swagger UI (Mặc định là /swagger-ui.html)
    disable-swagger-default-url: true # Tắt URL mặc định nếu muốn
openapi:
  dev-url: http://localhost:8080
  prod-url: https://api-ansinhso.personal-huytd.io.vn

minio:
  url: ${MINIO_URL:https://cdn-ansinhso.personal-huytd.io.vn}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: ${MINIO_BUCKET:my-bucket}

jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-at-least-256-bits-long-for-hs256-algorithm}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds